### ISSUE TITLE
New Pokemon

### ISSUE THREAD

**Issue by jeffsetter** [kimjudyh/pogo_pvp_fullstack#33]
Add new pokemon (Hisuian region, and violet/scarlet as it comes out)

Hisuian stats are here: https://pokemongohub.net/post/news/hisuian-pokemon-stats-in-pokemon-go/

**Comment by jeffsetter** [comment]
Paldean stats are here: https://docs.google.com/spreadsheets/d/1QDk6pGO6hbh3GrdeJp_0bx-xVMiG0zYAfpWZUV7ZaME/edit#gid=2086068356

**Comment by jason-setter** [comment]
So I guess I can figure out how to do this

**Comment by jeffsetter** [comment]
Implemented by https://github.com/kimjudyh/pogo_pvp_fullstack/pull/34
